#######The following codes reference published literature
#####Youngblut, Nicholas D., et al. "Host diet and evolutionary history explain different aspects of gut microbiome diversity among vertebrate clades." Nature communications 10.1 (2019): 1-15.
library(cluster)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(phyloseq)
library(vegan)
library(geosphere)
library(ecodist)
library(doParallel)
set.seed(123)
########
# load alpha-div values
alpha_div = readRDS("alpha_div.RDS")
alpha_div = do.call(cbind, alpha_div)
alpha_div$X.SampleID = rownames(alpha_div)
########functions
as.Num = function(x){
  as.numeric(as.character(x))
}
dist_mtx_order = function(d, x){
  # Ordering distance matrixes
  # d = distance matrix (dist class)
  # x = vector to order dist. obj. by
  m = d %>% as.matrix
  d = as.dist(m[x,x])
  return(d)
}
rescale_dist_mtx = function(m){
  m = m %>% as.matrix
  labs = m %>% colnames
  n_row = m %>% nrow
  n_col = m %>% ncol
  x = m %>% as.vector 
  x = scales::rescale(x) 
  m = matrix(x, nrow=n_row, ncol=n_col)
  colnames(m) = labs
  rownames(m) = labs
  m = m %>% as.dist
  return(m)
}
##########
metadata<- read.delim('2.tsv', sep = '\t',row.names = 1)%>%
  mutate(X.SampleID = rownames(.))#read metadata
##########
#convert alpha diversity to gower distance
alpha_div_mtx = list()
n = ncol(alpha_div) -1 
for(x in colnames(alpha_div)[1:n]){
  y = as.data.frame(alpha_div[,x])
  rownames(y) = rownames(alpha_div)
  alpha_div_mtx[[x]] = cluster::daisy(y, metric='gower')
}
alpha_div = alpha_div_mtx
#################
#Diet (detailed) distance
dietD = metadata %>%
  dplyr::select(X.SampleID, diet_vertebrate, diet_invertebrate, diet_fruit,
                diet_flowers_nectar_pollen, diet_leaves_branches_bark_buds, diet_seeds,
                diet_grass_waterplants, diet_roots_tubers) %>%
  mutate(diet_invertebrate = gsub(' .+', '', diet_invertebrate) %>% as.factor) %>%
  as.data.frame

rownames(dietD) = dietD$X.SampleID
dietD$X.SampleID = NULL

cn = colnames(dietD)
dietD = dietD %>% 
  apply(1, function(x) ifelse(x=='yes', 1, 0)) %>%
  t %>% as.data.frame
colnames(dietD) = cn
dietD_d = vegan::vegdist(dietD, metric='jaccard')#jaccard¾àÀë
#################
#Habitat distance
habitatD = metadata %>%
  dplyr::select(X.SampleID, habitat_detail, habitat_detail_1, habitat_detail_2) %>%
  as.data.frame

rownames(habitatD) = habitatD$X.SampleID
habitatD$X.SampleID = NULL
habitatD_d = cluster::daisy(habitatD, metric='gower')
################
#Geographic distance
geo = metadata %>% 
  dplyr::select(X.SampleID, latitude, longitude) %>%
  mutate(latitude = latitude %>% as.Num,
         longitude = longitude %>% as.Num) %>%
  as.data.frame

rownames(geo) = geo$X.SampleID
.pairwise_distGeo = function(x, y){
  d = geosphere::distGeo(x[c('longitude', 'latitude')],
                         y[,c('longitude', 'latitude')])
  return(d)
}

pairwise_distGeo = function(df){
  x = df[,c('longitude', 'latitude')]
  geo_d = apply(x, 1, .pairwise_distGeo, y=x)
  rescale_dist_mtx(as.dist(geo_d))
}

geo_d = pairwise_distGeo(geo)
###############
#Sampling details distance
samp = metadata %>% 
  dplyr::select(X.SampleID,sample_type, captive_wild) 

rownames(samp) = samp$X.SampleID
samp$X.SampleID = NULL
samp_d = cluster::daisy(samp, metric='gower')
###############
#Order matrices
alpha_div %>% labels
# ordering by beta-div metrix
X = labels(alpha_div$shannon)
dietD_d_o = dist_mtx_order(dietD_d, X)
habitatD_d_o = dist_mtx_order(habitatD_d, X)
geo_d_o = dist_mtx_order(geo_d, X)
samp_d_o = dist_mtx_order(samp_d, X)
# check
X %>% length %>% print
###############
#MRM intra-spec sensitivity
# number of permutated SpecD datasetst
nperm_datasets = 100
# number of permutations per MRM analysis
nperm = 1000
#Functions
#' randomly selecting one per group
#' L : list of distance matrixes used for MRM
#' df_grps : data.frame (sample, group)
one_per_group = function(L, df_grps, ...){
  # get subsample
  colnames(df_grps) = c('Sample', 'Group')
  df_grps = df_grps %>%
    group_by(Group) %>%
    sample_n(1)
  # subsetting all matrices
  lapply(L, function(x) dist_mtx_order(x, df_grps$Sample))
}
#' MRM on one subsample rep
#' i : rep number
#' L : list of list of distance matrices generated by `one_per_group()`
# nperm : nperm function for MRM
# f : MRM fomulat
mrm_each = function(i, L, f, nperm=99){
  m = L[[i]]
  f = as.formula(f)
  x = ecodist::MRM(f, nperm=nperm, mrank=TRUE)
  # coefficients
  df = x$coef %>% as.data.frame
  colnames(df) = c('coef', 'coef_pval')
  df$variable = rownames(df)
  df$R2 = x$r.squared[1]
  df$pval = x$r.squared[2]
  df$F = x$F.test[1]
  df$rep = i
  return(df)
}
# renaming output
rename_df = data.frame(old_name = c('m$diet','m$geo','m$habitat', 'm$samp'),
                       new_name = c('Diet', 'Geography', 'Habitat', 'Technical'))
# grouping samples by species
df_grps = metadata %>% 
  filter(X.SampleID %in% labels(dietD_d_o)) %>%
  dplyr::select(X.SampleID, scientific_name)
###################
#Faith's PD
# creating subsample permutations of the distance matrices
L = list(alpha = alpha_div$faith_pd,
         diet = dietD_d_o,
         habitat = habitatD_d_o,
         geo = geo_d_o,
         samp = samp_d_o)

m_perm = lapply(as.list(1:nperm_datasets), function(x) one_per_group(L, df_grps, x))
#Model 2
doParallel::registerDoParallel(threads)
x = as.list(1:length(m_perm))
f = 'm$alpha ~  m$diet + m$habitat + m$geo + m$samp'
mrm_res = plyr::llply(x, mrm_each, L=m_perm, f=f, nperm=nperm, .parallel=TRUE)
mrm_res = do.call(rbind, mrm_res)
mrm_res_s = mrm_res %>% 
  filter(variable != 'Int') %>%
  gather(category, value, -variable, -R2, -pval, -F, -rep) %>%
  mutate(category = ifelse(category == 'coef', 'Coef.', 'Adj. P-value'))

mrm_res_s = mrm_res_s %>%
  inner_join(rename_df, c('variable'='old_name')) %>%
  dplyr::select(-variable) %>%
  rename('variable' = new_name)             

# changing coef scale
df = mrm_res_s %>%
  filter(category == 'Coef.') %>%
  mutate(value = 0.41) %>%
  .[1,]
p = ggplot(mrm_res_s, aes(variable, value)) +
  geom_boxplot() +
  geom_point(data=df, alpha=0) +
  facet_grid(category ~ ., scales='free_y') +
  theme_bw()
# significance
mrm_res %>% 
  group_by(variable) %>%
  summarize(pval_sensitivity = 1 - sum(coef_pval < 0.05) / length(pval)) %>%
  ungroup() %>%
  mutate(sig_pval_sensitivity = pval_sensitivity < 0.05)
##########Êä³öÍ¼Æ¬
plot_write = function(p, file=NULL, path=NULL, width=NA, height=NA, ...){
  # file path
  if(is.null(path)){
    path = file.path(getwd(), '.figures')
    if(! dir.exists(path)){
      dir.create(path, showWarnings=FALSE)
    }
  }
  # file name
  if(is.null(file)){
    file = paste0(fig_uuid(), '.pdf')
  } 
  file = file.path(path, file)
  
  # width & height
  if(is.na(width)){
    width = options()$repr.plot.width
  }
  if(is.na(height)){
    height = options()$repr.plot.height
  }
  # writting figure
  if(length(class(p)) >= 2 & class(p)[2] == 'ggplot2'){
    ggplot2::ggsave(filename=file, plot=p, width=width, height=height, ...)
  } else {
    pdf(file=file, width=width, height=height)
    plot(p, ...)
    dev.off()
  }
  cat('File written:', file, '\n')
  # plotting
  plot(p)
}
plot_write(p, file='IndD_MRM_alpha.pdf')
